server:
  port: 9001
spring:
  application:
    name: tenaquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.47.136:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    generate‚Äêddl: true